"""
Constacyclic code search over GF(4) for quantum error-correcting codes.

Constacyclic codes use x^n - alpha (alpha in GF(4), alpha != 0,1) as the
modulus instead of x^n - 1 (cyclic codes). This gives different polynomial
factorizations and potentially different codes.

For GF(4) = {0, 1, omega, omega^2} with omega^2 + omega + 1 = 0:
  - alpha = omega gives omega-constacyclic codes
  - alpha = omega^2 gives omega^2-constacyclic codes

KEY CONSTRUCTION: For an alpha-constacyclic code C generated by g(x) that
divides x^n - alpha, the constacyclic shift T maps (c_0,...,c_{n-1}) to
(alpha*c_{n-1}, c_0,...,c_{n-2}). If a vector v in C is self-orthogonal
under the Hermitian inner product, then v, Tv, T^2v, ... give a set of
stabilizers for a quantum code, provided mutual orthogonality holds.

We systematically:
1. Factor x^n - alpha over GF(4) for alpha in {omega, omega^2}
2. For each generator polynomial g(x), build the code and its constacyclic shifts
3. Find maximal Hermitian self-orthogonal subcodes using the shift structure
4. Compute quantum code parameters and compare against known bounds

Connection: the project found [[13,1,5]] via quasi-twisted with twist=omega;
constacyclic codes are the algebraic foundation of that construction.

Usage:
    cd ~/workspace/qec-search && venv/bin/python3 engine/constacyclic_search.py
"""

import numpy as np
import galois
import signal
import time
import os
import sys
import functools
from itertools import combinations
from math import gcd

# Nice priority
os.nice(15)

# Flush prints
print = functools.partial(print, flush=True)

sys.path.insert(0, os.path.dirname(__file__))
from symplectic import StabilizerCode, compute_distance_qldpc
from gf4_codes import (gf4_to_symplectic, is_hermitian_self_orthogonal,
                        hermitian_inner_product)
from known_codes import KNOWN_BOUNDS
from codes import gf2_rank

# ---------------------------------------------------------------------------
# GF(4) field setup
# ---------------------------------------------------------------------------
GF4 = galois.GF(4)
GF2 = galois.GF(2)
OMEGA = GF4.primitive_element       # omega (element 2)
OMEGA2 = OMEGA ** 2                 # omega^2 (element 3)

# Timeouts
DIST_TIMEOUT = 30       # per code distance computation
PER_N_TIMEOUT = 120     # per block length


# ---------------------------------------------------------------------------
# Constacyclic shift operator
# ---------------------------------------------------------------------------

def constacyclic_shift(v, alpha):
    """Apply constacyclic shift: (c_0,...,c_{n-1}) -> (alpha*c_{n-1}, c_0,...,c_{n-2})."""
    n = len(v)
    result = np.zeros(n, dtype=int)
    result[0] = int(alpha * GF4(int(v[n - 1])))
    for i in range(1, n):
        result[i] = int(v[i - 1])
    return GF4(result)


def generate_shifts(v, alpha, n):
    """Generate all n constacyclic shifts of v."""
    shifts = [GF4(np.array(v))]
    current = v
    for _ in range(n - 1):
        current = constacyclic_shift(current, alpha)
        shifts.append(current)
    return shifts


# ---------------------------------------------------------------------------
# Polynomial arithmetic over GF(4)
# ---------------------------------------------------------------------------

def poly_to_vec(p, n):
    """Convert polynomial to length-n vector (coeff of x^i at index i)."""
    row = np.zeros(n, dtype=int)
    coeffs = p.coefficients()[::-1]
    for i in range(min(len(coeffs), n)):
        row[i] = int(coeffs[i])
    return row


def build_code_matrix(g, n, alpha):
    """Build generator matrix for alpha-constacyclic code with generator g(x).

    Rows: g(x), x*g(x), ..., x^{k-1}*g(x) mod (x^n - alpha)
    """
    modulus = galois.Poly(GF4([1] + [0] * (n - 1) + [alpha]), field=GF4)
    deg_g = g.degree
    k_code = n - deg_g
    if k_code < 1:
        return None

    rows = []
    current = g
    x_poly = galois.Poly([GF4(1), GF4(0)], field=GF4)
    for _ in range(k_code):
        rows.append(poly_to_vec(current, n))
        current = (current * x_poly) % modulus

    return GF4(np.array(rows))


# ---------------------------------------------------------------------------
# Self-orthogonal subcode via constacyclic shifts
# ---------------------------------------------------------------------------

def find_shift_orthogonal_code(seed_vec, alpha, n):
    """Given a seed vector in a constacyclic code, generate its shifts
    and select a maximal mutually Hermitian-orthogonal subset.

    The constacyclic shift preserves the code structure. If seed_vec is
    self-orthogonal and <v, Tv> = 0, then all consecutive shifts are
    mutually orthogonal (by the constacyclic structure).

    Returns GF4 matrix of selected rows, or None.
    """
    seed = GF4(np.array(seed_vec))

    # Check self-orthogonality
    if hermitian_inner_product(seed, seed) != GF4(0):
        return None

    # Generate all shifts
    shifts = generate_shifts(seed, alpha, n)

    # Greedily select mutually orthogonal shifts
    selected = [shifts[0]]
    for i in range(1, len(shifts)):
        ok = True
        for s in selected:
            if hermitian_inner_product(shifts[i], s) != GF4(0):
                ok = False
                break
        if ok:
            # Check GF(2) independence
            test_mat = GF4(np.array([list(r) for r in selected + [shifts[i]]]))
            test_sym = gf4_to_symplectic(test_mat)
            prev_mat = GF4(np.array([list(r) for r in selected]))
            prev_sym = gf4_to_symplectic(prev_mat)
            if gf2_rank(test_sym) > gf2_rank(prev_sym):
                selected.append(shifts[i])

    if len(selected) < 1:
        return None

    H = GF4(np.array([list(r) for r in selected]))
    if not is_hermitian_self_orthogonal(H):
        return None
    return H


def find_multi_seed_code(seeds, alpha, n):
    """Combine shifts from multiple seed vectors into a larger stabilizer code.

    Takes seeds that are pairwise Hermitian-orthogonal and generates
    their constacyclic shifts, selecting a maximal self-orthogonal set.
    """
    all_shifts = []
    for seed in seeds:
        shifts = generate_shifts(seed, alpha, n)
        all_shifts.extend(shifts)

    # Also add omega * each shift and omega^2 * each shift
    extended = list(all_shifts)
    for v in all_shifts:
        extended.append(OMEGA * v)
        extended.append(OMEGA2 * v)

    # Remove duplicates and zero vectors
    seen = set()
    unique = []
    for v in extended:
        key = tuple(int(x) for x in v)
        if key not in seen and any(x != 0 for x in key):
            seen.add(key)
            unique.append(v)

    # Greedy selection
    selected = []
    selected_sym = None

    for v in unique:
        # Self-orthogonal?
        if hermitian_inner_product(v, v) != GF4(0):
            continue

        # Mutually orthogonal?
        ok = True
        for s in selected:
            if hermitian_inner_product(v, s) != GF4(0):
                ok = False
                break
        if not ok:
            continue

        # Independent?
        v_sym = gf4_to_symplectic(GF4(np.array(v).reshape(1, -1)))
        if selected_sym is not None:
            test_sym = np.vstack([selected_sym, v_sym])
            if gf2_rank(test_sym) <= gf2_rank(selected_sym):
                continue
            selected_sym = test_sym
        else:
            selected_sym = v_sym

        selected.append(v)
        if len(selected) >= n - 1:
            break

    if len(selected) < 1:
        return None

    H = GF4(np.array([list(r) for r in selected]))
    if not is_hermitian_self_orthogonal(H):
        return None
    return H


# ---------------------------------------------------------------------------
# Evaluate quantum code
# ---------------------------------------------------------------------------

def evaluate_code(H_gf4, n):
    """Compute [[n,k,d]] and compare against known bounds."""
    sym_H = gf4_to_symplectic(H_gf4)
    code = StabilizerCode(H=sym_H, n=n)

    valid, _ = code.is_valid()
    if not valid:
        return None

    k = code.k
    if k < 1:
        return None

    # Skip codes with very high k -- distance computation is exponential in
    # centralizer dimension which grows with k. For n >= 20, limit k.
    if n >= 20 and k > 10:
        return None
    if n >= 15 and k > 12:
        return None

    # Adaptive timeout: shorter for larger codes
    timeout = min(DIST_TIMEOUT, max(10, 60 - n))

    d = compute_distance_qldpc(code, timeout_sec=timeout)
    if d is None or d < 2:
        return None

    key = (n, k)
    status = ""
    if key in KNOWN_BOUNDS:
        dl, du = KNOWN_BOUNDS[key]
        if d > dl:
            status = f" *** IMPROVEMENT over known d={dl} ***"
        elif d == dl:
            status = f" MATCHES(d={dl})"
        elif d >= dl - 1:
            status = f" close(known={dl})"
        else:
            status = f" (known={dl})"
    else:
        status = " [no bound]"

    return n, k, d, status


# ---------------------------------------------------------------------------
# Search a single n
# ---------------------------------------------------------------------------

def search_single_n(n, rng=None):
    """Search constacyclic codes for block length n."""
    if rng is None:
        rng = np.random.default_rng(42)

    start = time.time()
    results = []
    best_per_k = {}  # k -> (d, info)

    alphas = [(OMEGA, "w"), (OMEGA2, "w2")]

    for alpha, alpha_name in alphas:
        if time.time() - start > PER_N_TIMEOUT:
            break

        # Factor x^n + alpha (= x^n - alpha in char 2)
        # Use SIGALRM to timeout galois factorization for large n
        modulus = galois.Poly(GF4([1] + [0] * (n - 1) + [alpha]), field=GF4)

        class FactorTimeout(Exception):
            pass

        def _alarm_handler(signum, frame):
            raise FactorTimeout()

        old_handler = signal.signal(signal.SIGALRM, _alarm_handler)
        signal.alarm(30)  # 30s timeout for factorization
        try:
            factors, mults = modulus.factors()
            signal.alarm(0)
        except FactorTimeout:
            signal.alarm(0)
            signal.signal(signal.SIGALRM, old_handler)
            print(f"  a={alpha_name}: factorization timeout (n={n})")
            continue
        finally:
            signal.signal(signal.SIGALRM, old_handler)

        factor_degs = [f.degree for f in factors]
        print(f"  a={alpha_name}: factors={factor_degs}", end="")

        # Skip if all non-trivial factors are too large (no useful combinations)
        nontrivial_degs = [d for d in factor_degs if d > 1]
        if nontrivial_degs and min(nontrivial_degs) > n // 2:
            print(" -- skipping (factors too large)")
            continue

        # Enumerate generator polynomials (products of factor subsets)
        total_gens = 1
        for m in mults:
            total_gens *= (m + 1)

        max_combo = min(len(factors), 6)  # Cap combinatorial explosion
        generator_polys = []

        for r in range(1, max_combo + 1):
            for combo in combinations(range(len(factors)), r):
                g = galois.Poly([GF4(1)], field=GF4)
                for idx in combo:
                    for _ in range(mults[idx]):
                        g = g * factors[idx]

                deg_g = g.degree
                if 0 < deg_g < n:
                    generator_polys.append((g, combo))

        print(f", {len(generator_polys)} generators")

        for g, combo in generator_polys:
            if time.time() - start > PER_N_TIMEOUT:
                break

            deg_g = g.degree
            k_classical = n - deg_g

            # Build the GF(4)-linear code matrix
            H_linear = build_code_matrix(g, n, alpha)
            if H_linear is None:
                continue

            # Strategy 1: Use each row as a seed for shift-based construction
            for row_idx in range(H_linear.shape[0]):
                seed = H_linear[row_idx]
                H = find_shift_orthogonal_code(seed, alpha, n)
                if H is None:
                    continue

                result = evaluate_code(H, n)
                if result is not None:
                    _, k, d, status = result
                    if k not in best_per_k or d > best_per_k[k][0]:
                        best_per_k[k] = (d, f"a={alpha_name},g=deg{deg_g},shift")
                        print(f"    [[{n},{k},{d}]] shift(row{row_idx}){status}")
                        results.append((n, k, d, status, alpha_name,
                                        f"shift from g=deg{deg_g}"))

            # Strategy 2: Use omega*row and omega^2*row as seeds too
            for row_idx in range(min(H_linear.shape[0], 3)):
                for scalar in [OMEGA, OMEGA2]:
                    seed = scalar * H_linear[row_idx]
                    H = find_shift_orthogonal_code(seed, alpha, n)
                    if H is None:
                        continue

                    result = evaluate_code(H, n)
                    if result is not None:
                        _, k, d, status = result
                        if k not in best_per_k or d > best_per_k[k][0]:
                            best_per_k[k] = (d, f"a={alpha_name},scaled")
                            print(f"    [[{n},{k},{d}]] scaled-shift{status}")
                            results.append((n, k, d, status, alpha_name,
                                            f"scaled shift from g=deg{deg_g}"))

            # Strategy 3: Combine seeds from the code
            if k_classical >= 2:
                for i in range(min(k_classical, 4)):
                    for j in range(i + 1, min(k_classical, 5)):
                        if time.time() - start > PER_N_TIMEOUT:
                            break
                        seeds = [H_linear[i], H_linear[j]]
                        H = find_multi_seed_code(seeds, alpha, n)
                        if H is None:
                            continue
                        result = evaluate_code(H, n)
                        if result is not None:
                            _, k, d, status = result
                            if k not in best_per_k or d > best_per_k[k][0]:
                                best_per_k[k] = (d, f"a={alpha_name},multi")
                                print(f"    [[{n},{k},{d}]] multi-seed{status}")
                                results.append((n, k, d, status, alpha_name,
                                                f"multi-seed from g=deg{deg_g}"))

            # Strategy 4: GF(2) sums of rows as seeds
            for i in range(min(k_classical, 4)):
                for j in range(i + 1, min(k_classical, 5)):
                    if time.time() - start > PER_N_TIMEOUT:
                        break
                    sum_row = H_linear[i] + H_linear[j]
                    if np.all(np.array(sum_row) == 0):
                        continue
                    H = find_shift_orthogonal_code(sum_row, alpha, n)
                    if H is None:
                        continue
                    result = evaluate_code(H, n)
                    if result is not None:
                        _, k, d, status = result
                        if k not in best_per_k or d > best_per_k[k][0]:
                            best_per_k[k] = (d, f"a={alpha_name},sum")
                            print(f"    [[{n},{k},{d}]] sum-seed{status}")
                            results.append((n, k, d, status, alpha_name,
                                            f"sum-seed from g=deg{deg_g}"))

            # Strategy 5: Random GF(4) combinations as seeds
            for _ in range(min(20, k_classical * 3)):
                if time.time() - start > PER_N_TIMEOUT:
                    break
                coeffs = GF4(rng.integers(0, 4, size=k_classical))
                if np.all(np.array(coeffs) == 0):
                    continue
                seed = GF4(np.zeros(n, dtype=int))
                for idx in range(k_classical):
                    seed = seed + coeffs[idx] * H_linear[idx]
                if np.all(np.array(seed) == 0):
                    continue

                H = find_shift_orthogonal_code(seed, alpha, n)
                if H is None:
                    continue
                result = evaluate_code(H, n)
                if result is not None:
                    _, k, d, status = result
                    if k not in best_per_k or d > best_per_k[k][0]:
                        best_per_k[k] = (d, f"a={alpha_name},rand")
                        print(f"    [[{n},{k},{d}]] rand-seed{status}")
                        results.append((n, k, d, status, alpha_name,
                                        f"random seed from g=deg{deg_g}"))

        # Strategy 6: For rich factorizations, try combining codewords across
        # different generator polynomials
        if len(generator_polys) >= 4 and time.time() - start < PER_N_TIMEOUT:
            for _ in range(min(30, len(generator_polys))):
                if time.time() - start > PER_N_TIMEOUT:
                    break
                # Pick two random generator polys
                idx1, idx2 = rng.choice(len(generator_polys), 2, replace=False)
                g1, _ = generator_polys[idx1]
                g2, _ = generator_polys[idx2]

                H1 = build_code_matrix(g1, n, alpha)
                H2 = build_code_matrix(g2, n, alpha)
                if H1 is None or H2 is None:
                    continue

                # Pick random rows from each and combine as multi-seed
                r1 = rng.integers(0, H1.shape[0])
                r2 = rng.integers(0, H2.shape[0])
                seeds = [H1[r1], H2[r2]]
                H = find_multi_seed_code(seeds, alpha, n)
                if H is None:
                    continue
                result = evaluate_code(H, n)
                if result is not None:
                    _, k, d, status = result
                    if k not in best_per_k or d > best_per_k[k][0]:
                        best_per_k[k] = (d, f"a={alpha_name},cross")
                        print(f"    [[{n},{k},{d}]] cross-gen{status}")
                        results.append((n, k, d, status, alpha_name,
                                        f"cross-generator"))

    elapsed = time.time() - start
    print(f"  n={n}: {len(results)} codes ({elapsed:.1f}s)")
    return results


# ---------------------------------------------------------------------------
# Main search
# ---------------------------------------------------------------------------

def search_constacyclic(n_min=5, n_max=25):
    """Run constacyclic search for all odd n in [n_min, n_max]."""
    start_time = time.time()

    all_results = []
    matches = []
    improvements = []

    rng = np.random.default_rng(42)

    for n in range(n_min, n_max + 1):
        if gcd(n, 2) != 1:
            continue

        print(f"\n{'='*60}")
        print(f"n = {n}")
        print(f"{'='*60}")

        results = search_single_n(n, rng=rng)
        all_results.extend(results)

        for entry in results:
            status = entry[3]
            if "MATCHES" in status:
                matches.append(entry)
            elif "IMPROVEMENT" in status:
                improvements.append(entry)

    # Summary
    elapsed = time.time() - start_time
    print(f"\n{'='*60}")
    print("CONSTACYCLIC SEARCH COMPLETE")
    print(f"{'='*60}")
    print(f"Time: {elapsed:.1f}s")
    print(f"Total codes found: {len(all_results)}")

    if improvements:
        print(f"\n*** IMPROVEMENTS ({len(improvements)}) ***")
        for n, k, d, status, alpha_name, info in improvements:
            print(f"  [[{n},{k},{d}]] {info}")

    if matches:
        print(f"\nMATCHES ({len(matches)}):")
        for n, k, d, status, alpha_name, info in matches:
            print(f"  [[{n},{k},{d}]] {info}")

    # Best per (n,k)
    if all_results:
        print(f"\nBEST CODES PER (n,k):")
        best = {}
        for entry in all_results:
            n, k, d, status, alpha_name, info = entry
            key = (n, k)
            if key not in best or d > best[key][2]:
                best[key] = entry
        for key in sorted(best.keys()):
            n, k, d, status, alpha_name, info = best[key]
            print(f"  [[{n},{k},{d}]]{status}")

    return all_results, matches, improvements


if __name__ == "__main__":
    print("=" * 60)
    print("CONSTACYCLIC CODE SEARCH OVER GF(4)")
    print("=" * 60)
    print(f"Searching n = 5..25 (odd), alpha in {{omega, omega^2}}")
    print(f"Dist timeout: {DIST_TIMEOUT}s, per-n: {PER_N_TIMEOUT}s")
    print()

    all_results, matches, improvements = search_constacyclic(n_min=5, n_max=25)
